---
title: "Gapminder Analysis Dplyr"
author: "Lina Barbosa"
date: "16 de abril de 2016"
output: html_document
---

## Load packages 

```{r setup, echo = FALSE, warning=FALSE}

library(dplyr)
library(ggplot2)
library(gapminder)
```


## Exploration with gapminder and dplyr 

```{r, echo=FALSE, include=FALSE}

# Subset rows
filter(gapminder, lifeExp<29)
filter(gapminder, country=="Rwanda")
a=filter(gapminder, country %in% c("Rwanda", "Afghanistan"))

# the pipe operator! %>%
# from magrittr package 

gapminder %>% head
head(gapminder) # same as 

head(gapminder, 3)
gapminder %>% head(3)

# select variables with select

select(gapminder, year, lifeExp) # great, but!

# select with pipe

gapminder %>% select(year, lifeExp)

# take whatever is on the left of the %>% and passes it to whatever is on the right, as the first argument 

gapminder %>% 
  select(year, lifeExp) %>% 
  head(4)

# calculate the mean of GDP in cambodia

gapminder %>% 
  filter(country=="Cambodia") %>% 
  select(country, year, pop, gdpPercap)

# Another way to use select 
gapminder %>% 
  filter(country=="Cambodia") %>% 
  select(-continent, -lifeExp)

# Compare with basic R

gapminder[gapminder$country=="Cambodia", c("country", "year", "pop", "gdpPercap")] # Not that nice

# Continue with mutate

gapminder %>% 
  mutate(gdp=pop*gdpPercap)

# Exercise, add mutate to previus analsis

gapminder %>% 
  filter(country=="Cambodia") %>% 
  select(-continent, -lifeExp) %>% 
  mutate(gdp=pop*gdpPercap)

# Now calculate the mean gdp | summarize data 
gapminder %>% 
  filter(country=="Cambodia") %>% 
  select(-continent, -lifeExp) %>% 
  mutate(gdp=pop*gdpPercap) %>% 
  group_by(country) %>% 
  summarise(mean_gdp=mean(gdp)) %>% 
  ungroup() # clean up, do this if you group_by!

# all countries 
gapminder %>% 
  #filter(country=="Cambodia") %>% 
  select(-continent, -lifeExp) %>% 
  mutate(gdp=pop*gdpPercap) %>% 
  group_by(country) %>% 
  summarise(mean_gdp=mean(gdp)) %>% 
  ungroup()
```


```{r }

```


